AUGMENTATION: True
IMAGE_SIZE: [160, 160, 3]
BATCH_SIZE: 32
INCLUDE_TOP: False
EPOCHS: 5
CLASSES: 4          # you can set to actual or let code detect automatically
WEIGHTS: imagenet
LEARNING_RATE: 0.001
